---
- name: Provision and configure a server
  hosts: all
  become: true
  tasks:
    - name: Ensure the server is updated
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx  # Replace with any software package needed
        - git

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true
